In [1208]:
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Annotated

import numpy as np

from geneticengine.grammar.metahandlers.ints import IntRange
from geneticengine.grammar import extract_grammar
from geneticengine.problems import SingleObjectiveProblem, MultiObjectiveProblem
from geneticengine.random.sources import NativeRandomSource
from geneticengine.algorithms.gp.gp import GeneticProgramming
from geneticengine.evaluation.budget import TimeBudget, EvaluationBudget
from geneticengine.representations.tree.initializations import MaxDepthDecider
from geneticengine.representations.tree.treebased import TreeBasedRepresentation
from geneticengine.evaluation.recorder import CSVSearchRecorder
from geneticengine.evaluation.tracker import ProgressTracker

from sklearn.datasets import load_breast_cancer

import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

import time

In [1209]:
# df = pd.read_csv('fraud_dataset.csv')
#read breast cancer dataset
df = load_breast_cancer(as_frame=True).frame
df.head(3)

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0

[3 rows x 31 columns]

In [1210]:
split_percentage = 0.8
split_point = int(len(df) * split_percentage)

# 3. Create the train and test sets
train_df = df.iloc[:split_point]
test_df = df.iloc[split_point:]

# 4. Separate features (X) and target (y) for each set
# Assuming 'is_fraud' is your target column
X_train = train_df.drop('target', axis=1)
y_train = train_df['target']
X_test = test_df.drop('target', axis=1)
y_test = test_df['target']

In [1211]:
feature_names = X_train.columns.tolist()
n_features = len(feature_names)

In [1212]:
class Value(ABC):
    def evaluate(self):
        pass

class Scalar(ABC):
    pass

class Vectorial(ABC):
    pass

In [1213]:
@dataclass
class PastValues(Vectorial):
    index: Annotated[int, IntRange(0, n_features-1)]
    lockback: Annotated[int, IntRange(5, 10)]

    def evaluate(self, X, i):
        start_index = max(0, i-self.lockback+1)
        values = X.iloc[start_index: i+1, self.index].values
        if len(values) < self.lockback: #if there are not enough past values
            padding = np.zeros(self.lockback - len(values))
            values = np.concatenate((padding, values))
        return values
    def __str__(self):
        return f"past_values({feature_names[self.index]}, {self.lockback})"

In [1214]:
@dataclass
class Mean(Scalar):
    arr: Vectorial
    def evaluate(self, X, i):
        v = self.arr.evaluate(X,i)
        return np.mean(v)
    def __str__(self):
        return f"mean({self.arr})"
    
@dataclass
class Max(Scalar):
    arr: Vectorial
    def evaluate(self, X, i):
        v = self.arr.evaluate(X,i)
        return np.max(v)
    def __str__(self):
        return f"max({self.arr})"
    
@dataclass
class Min(Scalar):
    arr: Vectorial
    def evaluate(self, X, i):
        v = self.arr.evaluate(X,i)
        return np.min(v)
    def __str__(self):
        return f"min({self.arr})"

In [1215]:
@dataclass #Scalar Features (1)
class ScalarVar(Scalar): 
    index: Annotated[int, IntRange(0,n_features-1)]

    def evaluate(self, X, i):
        return X.iloc[i, self.index]
    
    def __str__(self):
        return feature_names[self.index]

# @dataclass #Vectorial Features ([1,2,3,4])
# class VectorialVar(Vectorial):
#     index: Annotated[int, IntRange(1,2)]
    
#     def evaluate(self, X):
#         return X[self.index]

In [1216]:
#scalar -> scalar
@dataclass 
class Add(Scalar):
    right: Scalar
    left: Scalar

    def evaluate(self, X, i):
        return self.left.evaluate(X,i) + self.right.evaluate(X,i)
    
    def __str__(self):
        return f"({self.left} + {self.right})"

In [1217]:
grammar = extract_grammar([PastValues, Mean, Max, Min, ScalarVar, Add], Scalar)
print(f"Grammar: {repr(grammar)}")

Grammar: Grammar<Starting=Scalar,Productions={
Scalar -> Mean(arr: Vectorial)|
	Max(arr: Vectorial)|
	Min(arr: Vectorial)|
	ScalarVar(index: Annotated[int])|
	Add(right: Scalar, left: Scalar)

Vectorial -> PastValues(index: Annotated[int], lockback: Annotated[int])
}

In [ ]:
def fitness_function(individual: Value):    
    start = time.perf_counter()

    train_feature = [individual.evaluate(X_train, i) for i in range(len(X_train))]
    test_feature = [individual.evaluate(X_test, i) for i in range(len(X_test))]
    
    X_train_new = np.array(train_feature).reshape(-1,1)
    X_test_new = np.array(test_feature).reshape(-1,1)

    model = DecisionTreeClassifier(random_state=42)
    model.fit(X_train_new, y_train)
    y_pred = model.predict_proba(X_test_new)[:, 1]

    elapsed = time.perf_counter() - start

    return float(elapsed), float(roc_auc_score(y_test, y_pred))

In [ ]:
prob = MultiObjectiveProblem(
    fitness_function=fitness_function,
    minimize=[False, True],
)
r = NativeRandomSource(123)
alg = GeneticProgramming(
    problem=prob,
    budget=TimeBudget(30),
    population_size=50,
    representation=TreeBasedRepresentation(grammar, MaxDepthDecider(r, grammar, 5)),
    random=r,
    tracker=ProgressTracker(
        prob,
        recorders=[CSVSearchRecorder(
            csv_path='outpupt.csv', 
            problem=prob, 
            fields={"Eval Time": lambda t,i,p: i.get_fitness(p).fitness_components[0],
                    "AUC": lambda t,i,p: i.get_fitness(p).fitness_components[1],
                    "Expression": lambda t, i, p: i.get_phenotype(),
                    },
            only_record_best_individuals=False)]
    )
    
)

solutions = alg.search()

In [1223]:
best_sol = max(solutions, key=lambda row: row.get_fitness(prob).fitness_components[1])
print(best_sol.get_phenotype(), best_sol.get_fitness(prob))

((worst smoothness + ((radius error + worst concavity) + (worst concavity + mean symmetry))) + min(past_values(mean concave points, 10))) [0.07256349999806844,0.9217657342657343]

In [1222]:
test = Max(arr=PastValues(index=feature_names.index('worst fractal dimension'), lockback=4))

generated_value = [test.evaluate(X_test, i) for i in range(len(X_test))]

test_df = X_test.copy()
test_df['generated'] = generated_value
test_df['target_x'] = y_test
test_df.head(10)

     mean radius  mean texture  ...  generated  target_x
455       13.380         30.72  ...    0.07675         1
456       11.630         29.29  ...    0.07675         1
457       13.210         25.25  ...    0.07675         1
458       13.000         25.13  ...    0.07675         1
459        9.755         28.20  ...    0.07220         1
460       17.080         27.15  ...    0.09060         0
461       27.420         26.27  ...    0.09060         0
462       14.400         26.99  ...    0.09060         1
463       11.600         18.36  ...    0.09060         1
464       13.170         18.22  ...    0.07863         1

[10 rows x 32 columns]