In [50]:
from analysis_helpers import (
    count_unique_columns,
    count_operators,
    calculate_tree_depth,
    calculate_expression_complexity,
)
import pandas as pd

In [51]:
df = pd.read_csv("../../gp_outputs/test.csv")
df.head(3)

   Execution Time                        Phenotype  Fitness0
0           0.015                 column_magnesium  0.941395
1           0.031                   column_proline  0.941395
2           0.046  (column_ash - column_magnesium)  0.941395

In [52]:
weight_config = {
    "w_operator" : 0.3,
    "w_column": 0.2,
    "w_depth": 0.5
}

In [53]:
# df['n_unique_features'] = df['Phenotype'].apply(count_unique_columns)
# df['n_operators'] = df['Phenotype'].apply(count_operators)
# df['tree_depth'] = df['Phenotype'].apply(calculate_tree_depth)
df['expression_complexity'] = df['Phenotype'].apply(lambda row: calculate_expression_complexity(row, weight_config))

In [54]:
df.head(10)

,Execution Time,Phenotype,Fitness0,expression_complexity
0,0.015,column_magnesium,0.941395,0.2
1,0.031,column_proline,0.941395,0.2
2,0.046,(column_ash - column_magnesium),0.941395,1.2
3,0.062,((((column_alcohol + column_total_phenols) + (column_alcalinity_of_ash - column_alcohol)) - ((column_hue - column_proanthocyanins) + (column_total_phenols - column_proline))) + (column_od280/od315_of_diluted_wines - column_nonflavanoid_phenols)),0.941395,6.3
4,0.078,((column_total_phenols + ((column_malic_acid - column_flavanoids) + (column_alcohol - column_color_intensity))) - column_hue),0.945528,4.7
5,0.093,(((column_hue - (column_proline + column_proanthocyanins)) - (column_ash + (column_flavanoids - column_alcohol))) - column_ash),0.951674,5.0
6,0.109,(column_alcohol + (((column_flavanoids - column_alcohol) + column_color_intensity) + column_proanthocyanins)),0.951674,4.0
7,0.125,(column_total_phenols - (column_od280/od315_of_diluted_wines - column_hue)),0.951674,2.2
8,0.234,((((column_nonflavanoid_phenols - column_nonflavanoid_phenols) + (column_total_phenols - column_alcalinity_of_ash)) - (column_nonflavanoid_phenols - (column_od280/od315_of_diluted_wines - column_total_phenols))) + ((column_od280/od315_of_diluted_wines + column_magnesium) - (column_flavanoids + (column_alcohol + column_nonflavanoid_phenols)))),0.951674,6.7
9,0.312,((((column_flavanoids - column_nonflavanoid_phenols) + column_magnesium) + column_nonflavanoid_phenols) - ((column_ash - column_nonflavanoid_phenols) - ((column_nonflavanoid_phenols - column_magnesium) + (column_flavanoids + column_malic_acid)))),0.952254,5.7

In [55]:
#show the 3rd row
df.loc[[3]]

,Execution Time,Phenotype,Fitness0,expression_complexity
3,0.062,((((column_alcohol + column_total_phenols) + (column_alcalinity_of_ash - column_alcohol)) - ((column_hue - column_proanthocyanins) + (column_total_phenols - column_proline))) + (column_od280/od315_of_diluted_wines - column_nonflavanoid_phenols)),0.941395,6.3