In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../gp_outputs/tests.csv")
df.head(3)

,Eval Time,Expression,F1 Score,Complexity
0,0.040989,column_MDVP_Shimmer,0.747374,0.2
1,0.036330,column_Shimmer_DDA,0.747374,0.2
2,0.035912,(((column_Shimmer_APQ3 + (column_MDVP_Flo_Hz_ ...,0.747374,7.1

In [3]:
df_sorted = df.sort_values(by='F1 Score', ascending=False)
df_sorted.head(50)

,Eval Time,Expression,F1 Score,Complexity
83,0.035730,(column_MDVP_Jitter_ - column_MDVP_RAP),0.774071,1.2
525,0.035963,(column_Shimmer_DDA + (column_MDVP_Jitter_ - c...,0.771354,2.2
636,0.037830,(column_Shimmer_DDA - column_PPE),0.756311,1.2
236,0.036841,column_MDVP_APQ,0.750092,0.2
225,0.036841,column_MDVP_APQ,0.750092,0.2
168,0.034267,((column_MDVP_RAP + ((column_MDVP_Jitter_Abs_ ...,0.750092,4.5
94,0.036841,column_MDVP_APQ,0.750092,0.2
199,0.035666,((column_MDVP_Shimmer - column_MDVP_Jitter_) -...,0.750092,2.2
237,0.035370,column_MDVP_APQ,0.750092,0.2
154,0.035105,((column_Shimmer_DDA + (column_MDVP_Flo_Hz_ - ...,0.750092,5.1
258,0.034719,column_MDVP_APQ,0.750092,0.2
295,0.034719,column_MDVP_APQ,0.750092,0.2
240,0.036841,column_MDVP_APQ,0.750092,0.2
299,0.035620,(((column_MDVP_Jitter_Abs_ + (column_Jitter_DD...,0.750092,5.0
322,0.037267,(column_Shimmer_APQ3 - column_MDVP_APQ),0.750092,1.2
230,0.036841,column_MDVP_APQ,0.750092,0.2
345,0.034719,column_MDVP_APQ,0.750092,0.2
18,0.036841,column_MDVP_APQ,0.750092,0.2
221,0.036841,column_MDVP_APQ,0.750092,0.2
144,0.036841,column_MDVP_APQ,0.750092,0.2
44,0.036841,column_MDVP_APQ,0.750092,0.2
234,0.036841,column_MDVP_APQ,0.750092,0.2
146,0.035308,column_MDVP_APQ,0.750092,0.2
395,0.034719,column_MDVP_APQ,0.750092,0.2
445,0.034719,column_MDVP_APQ,0.750092,0.2
484,0.069870,column_MDVP_APQ,0.750092,0.2
495,0.034719,column_MDVP_APQ,0.750092,0.2
502,0.038421,column_MDVP_APQ,0.750092,0.2
195,0.035308,column_MDVP_APQ,0.750092,0.2
545,0.034719,column_MDVP_APQ,0.750092,0.2
555,0.036418,(column_MDVP_Shimmer - (column_D2 - (column_MD...,0.750092,4.0
562,0.036745,(column_MDVP_APQ - column_Shimmer_APQ5),0.750092,1.2
595,0.034719,column_MDVP_APQ,0.750092,0.2
245,0.035308,column_MDVP_APQ,0.750092,0.2
645,0.034719,column_MDVP_APQ,0.750092,0.2
675,0.036304,column_MDVP_APQ,0.750092,0.2
14,0.034827,(column_RPDE - column_MDVP_Shimmer_dB_),0.747374,1.2
15,0.035476,((column_MDVP_Shimmer_dB_ + (column_MDVP_Jitte...,0.747374,5.6
16,0.037608,column_MDVP_Fhi_Hz_,0.747374,0.2
17,0.035413,column_MDVP_PPQ,0.747374,0.2
19,0.038658,column_MDVP_Fo_Hz_,0.747374,0.2
20,0.040902,((((column_MDVP_Fhi_Hz_ - column_Shimmer_DDA) ...,0.747374,5.5
693,0.037213,(column_Shimmer_APQ5 + column_NHR),0.747374,1.2
23,0.034838,column_MDVP_Fo_Hz_,0.747374,0.2
24,0.034727,column_MDVP_Flo_Hz_,0.747374,0.2
25,0.035657,(column_MDVP_Jitter_ + column_Jitter_DDP),0.747374,1.2
26,0.035971,((column_PPE + (column_MDVP_Fhi_Hz_ + column_M...,0.747374,5.2
27,0.035628,(((column_MDVP_Flo_Hz_ - (column_MDVP_Shimmer_...,0.747374,5.0
28,0.035355,column_MDVP_Jitter_Abs_,0.747374,0.2
29,0.035391,(column_spread2 - (((column_DFA + column_Shimm...,0.747374,5.5