In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("../../gp_outputs/tests.csv")
df.head(3)

,Eval Time,Expression,F1 Score,Complexity
0,0.021078,column_MDVP_Shimmer,0.736519,0.2
1,0.020645,(column_MDVP_Fhi_Hz_ + (((column_Shimmer_APQ3 - column_MDVP_RAP) - column_Shimmer_APQ3) + ((column_MDVP_RAP + column_Shimmer_DDA) - column_spread2))),0.717931,4.8
2,0.024859,(column_MDVP_Fo_Hz_ + (((column_MDVP_Fhi_Hz_ + column_PPE) - column_MDVP_Jitter_Abs_) + column_MDVP_Shimmer_dB_)),0.729691,4.2

In [49]:
df_sorted = df.sort_values(by='F1 Score', ascending=False)
df_sorted.head(50)

,Eval Time,Expression,F1 Score,Complexity
326,0.018277,((((column_MDVP_Shimmer - column_NHR) + column_MDVP_Jitter_) - column_spread1) + column_RPDE),0.753209,4.2
131,0.022559,(column_MDVP_PPQ - (((column_DFA - column_spread1) - (column_Shimmer_DDA + column_PPE)) - (column_Jitter_DDP + (column_D2 - column_MDVP_Jitter_)))),0.753209,5.7
481,0.018176,column_MDVP_APQ,0.747904,0.2
499,0.018292,column_MDVP_APQ,0.747904,0.2
296,0.019375,(((column_MDVP_Jitter_Abs_ + (column_Jitter_DDP + column_MDVP_APQ)) - (column_MDVP_Jitter_Abs_ - (column_MDVP_Jitter_ - column_MDVP_Shimmer))) - column_Shimmer_APQ3),0.747904,5.0
319,0.019978,(column_Shimmer_APQ3 - column_MDVP_APQ),0.747904,1.2
234,0.021061,column_MDVP_APQ,0.747904,0.2
255,0.018933,column_MDVP_APQ,0.747904,0.2
15,0.018453,column_MDVP_APQ,0.747904,0.2
687,0.018096,((column_MDVP_RAP - (column_MDVP_APQ - (column_spread1 - column_PPE))) - (((column_spread1 - column_MDVP_Shimmer) + column_Shimmer_APQ5) + (column_Jitter_DDP + (column_MDVP_Shimmer + column_MDVP_Shimmer)))),0.747904,6.1
670,0.018286,(column_MDVP_Jitter_ + (((column_D2 - column_Jitter_DDP) - column_RPDE) + ((column_MDVP_APQ + column_Shimmer_DDA) - (column_spread2 + column_RPDE)))),0.747904,5.5
143,0.021435,column_MDVP_APQ,0.747904,0.2
672,0.018790,column_MDVP_APQ,0.747904,0.2
151,0.020025,((column_Shimmer_DDA + (column_MDVP_Flo_Hz_ - (column_MDVP_Jitter_Abs_ + column_Shimmer_APQ3))) + (column_Shimmer_APQ3 - ((column_MDVP_APQ + column_MDVP_Jitter_Abs_) + column_MDVP_Flo_Hz_))),0.747904,5.1
165,0.018552,((column_MDVP_RAP + ((column_MDVP_Jitter_Abs_ + column_Shimmer_APQ5) - (column_Shimmer_APQ3 - column_MDVP_RAP))) + column_MDVP_APQ),0.747904,4.5
368,0.018091,((((column_DFA - column_spread2) - column_MDVP_RAP) - column_D2) - (((column_Shimmer_APQ3 + column_PPE) + (column_MDVP_APQ - column_NHR)) - ((column_NHR - column_MDVP_Shimmer_dB_) + column_MDVP_Shimmer))),0.747904,7.0
710,0.018145,column_MDVP_APQ,0.747904,0.2
764,0.018734,column_MDVP_APQ,0.747904,0.2
777,0.018412,column_MDVP_APQ,0.747904,0.2
374,0.018493,(column_RPDE - (((column_spread1 - column_MDVP_Flo_Hz_) + column_MDVP_Flo_Hz_) - ((column_Shimmer_APQ3 + column_Shimmer_APQ5) - (column_PPE - column_MDVP_Jitter_)))),0.746382,5.5
80,0.018649,(column_MDVP_Jitter_ - column_MDVP_RAP),0.741953,1.2
538,0.018082,column_spread1,0.741448,0.2
253,0.018513,((((column_spread1 - column_MDVP_PPQ) - (column_Shimmer_APQ3 - column_MDVP_Jitter_Abs_)) - (column_MDVP_RAP - (column_DFA - column_NHR))) - column_NHR),0.741448,5.5
60,0.017757,column_spread1,0.741448,0.2
520,0.019201,((column_spread1 + column_D2) + column_MDVP_Jitter_Abs_),0.741448,2.2
528,0.019335,column_spread1,0.741448,0.2
724,0.018502,((((column_Shimmer_APQ5 + column_spread1) + column_MDVP_Jitter_Abs_) - (column_Shimmer_DDA - (column_MDVP_Jitter_Abs_ + column_Shimmer_APQ3))) + column_MDVP_RAP),0.741448,5.0
762,0.018335,column_spread1,0.741448,0.2
562,0.018128,(((column_MDVP_PPQ - column_Shimmer_DDA) + column_MDVP_APQ) + column_spread1),0.741448,3.2
554,0.018422,column_spread1,0.741448,0.2
280,0.019272,((column_PPE - column_MDVP_Jitter_Abs_) - column_spread1),0.741448,2.2
645,0.018600,column_spread1,0.741448,0.2
194,0.019445,column_spread1,0.741448,0.2
210,0.017849,column_spread1,0.741448,0.2
152,0.019765,(column_spread1 - (column_DFA - (column_MDVP_APQ - column_Shimmer_DDA))),0.741448,3.2
156,0.018818,column_spread1,0.741448,0.2
463,0.018601,column_spread1,0.741448,0.2
462,0.018478,(column_Shimmer_APQ3 + (((column_spread1 + column_MDVP_RAP) + (column_Shimmer_APQ3 - column_MDVP_Jitter_)) + ((column_RPDE + column_DFA) - (column_DFA - column_PPE)))),0.741448,5.8
361,0.018251,column_spread1,0.741448,0.2
621,0.017812,(((column_MDVP_APQ + (column_Jitter_DDP - column_Jitter_DDP)) - ((column_MDVP_Fhi_Hz_ - column_Jitter_DDP) - column_Shimmer_DDA)) - ((column_MDVP_Shimmer - (column_MDVP_Fhi_Hz_ - column_MDVP_APQ)) - column_spread1)),0.741448,5.9
618,0.018253,(((column_Shimmer_DDA + (column_Jitter_DDP + column_NHR)) + ((column_spread1 + column_MDVP_APQ) + (column_Jitter_DDP - column_Jitter_DDP))) - ((column_PPE - column_PPE) - column_MDVP_Shimmer)),0.741448,6.1
84,0.018954,column_spread1,0.741448,0.2
104,0.017886,(column_D2 + column_spread1),0.741448,1.2
107,0.019062,column_spread1,0.741448,0.2
137,0.022391,((column_Shimmer_DDA - column_Jitter_DDP) - column_spread1),0.741448,2.2
383,0.018677,((column_Shimmer_APQ5 + column_MDVP_RAP) - (((column_RPDE - column_Shimmer_APQ5) + column_MDVP_Shimmer) + column_spread1)),0.741448,4.5
781,0.018379,((column_MDVP_Jitter_ - ((column_MDVP_Jitter_Abs_ + column_spread1) + (column_spread1 + column_MDVP_Shimmer_dB_))) + (column_PPE - ((column_MDVP_Jitter_ - column_MDVP_Jitter_) - column_RPDE))),0.741448,5.6
8,0.018151,column_spread1,0.741448,0.2
42,0.018151,column_spread1,0.741448,0.2
412,0.019127,(((column_MDVP_Shimmer_dB_ - (column_Shimmer_APQ5 + column_MDVP_Shimmer_dB_)) - column_spread1) - column_MDVP_PPQ),0.741448,4.0