In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("../../gp_outputs/tests.csv")
df.head(3)

,Eval Time,Expression,F1 Score,Complexity
0,0.020506,column_MDVP_Shimmer,0.736519,0.2
1,0.018151,column_Shimmer_DDA,0.736519,0.2
2,0.018021,((((column_MDVP_Fhi_Hz_ + column_Shimmer_APQ3) + (column_MDVP_PPQ - column_MDVP_Fo_Hz_)) - ((column_PPE - column_RPDE) + (column_Shimmer_APQ5 - column_D2))) + column_MDVP_Flo_Hz_),0.705216,6.2

In [52]:
df_sorted = df.sort_values(by='F1 Score', ascending=False)
df_sorted.head(50)

,Eval Time,Expression,F1 Score,Complexity
138,0.020395,(column_MDVP_PPQ - (((column_DFA - column_spread1) - (column_Shimmer_DDA + column_PPE)) - (column_Jitter_DDP + (column_D2 - column_MDVP_Jitter_)))),0.753209,5.7
333,0.019535,((((column_MDVP_Shimmer - column_NHR) + column_MDVP_Jitter_) - column_spread1) + column_RPDE),0.753209,4.2
699,0.017332,column_MDVP_APQ,0.747904,0.2
694,0.018349,((column_MDVP_RAP - (column_MDVP_APQ - (column_spread1 - column_PPE))) - (((column_spread1 - column_MDVP_Shimmer) + column_Shimmer_APQ5) + (column_Jitter_DDP + (column_MDVP_Shimmer + column_MDVP_Shimmer)))),0.747904,6.1
717,0.018300,column_MDVP_APQ,0.747904,0.2
21,0.017332,column_MDVP_APQ,0.747904,0.2
649,0.017332,column_MDVP_APQ,0.747904,0.2
599,0.017332,column_MDVP_APQ,0.747904,0.2
549,0.017332,column_MDVP_APQ,0.747904,0.2
375,0.024045,((((column_DFA - column_spread2) - column_MDVP_RAP) - column_D2) - (((column_Shimmer_APQ3 + column_PPE) + (column_MDVP_APQ - column_NHR)) - ((column_NHR - column_MDVP_Shimmer_dB_) + column_MDVP_Shimmer))),0.747904,7.0
449,0.017332,column_MDVP_APQ,0.747904,0.2
488,0.018095,column_MDVP_APQ,0.747904,0.2
679,0.018421,column_MDVP_APQ,0.747904,0.2
677,0.018790,(column_MDVP_Jitter_ + (((column_D2 - column_Jitter_DDP) - column_RPDE) + ((column_MDVP_APQ + column_Shimmer_DDA) - (column_spread2 + column_RPDE)))),0.747904,5.5
399,0.017332,column_MDVP_APQ,0.747904,0.2
349,0.017332,column_MDVP_APQ,0.747904,0.2
149,0.017332,column_MDVP_APQ,0.747904,0.2
150,0.020076,column_MDVP_APQ,0.747904,0.2
99,0.017332,column_MDVP_APQ,0.747904,0.2
158,0.021566,((column_Shimmer_DDA + (column_MDVP_Flo_Hz_ - (column_MDVP_Jitter_Abs_ + column_Shimmer_APQ3))) + (column_Shimmer_APQ3 - ((column_MDVP_APQ + column_MDVP_Jitter_Abs_) + column_MDVP_Flo_Hz_))),0.747904,5.1
199,0.017332,column_MDVP_APQ,0.747904,0.2
172,0.021918,((column_MDVP_RAP + ((column_MDVP_Jitter_Abs_ + column_Shimmer_APQ5) - (column_Shimmer_APQ3 - column_MDVP_RAP))) + column_MDVP_APQ),0.747904,4.5
299,0.017332,column_MDVP_APQ,0.747904,0.2
241,0.018546,column_MDVP_APQ,0.747904,0.2
262,0.019581,column_MDVP_APQ,0.747904,0.2
49,0.017332,column_MDVP_APQ,0.747904,0.2
326,0.018563,(column_Shimmer_APQ3 - column_MDVP_APQ),0.747904,1.2
303,0.019045,(((column_MDVP_Jitter_Abs_ + (column_Jitter_DDP + column_MDVP_APQ)) - (column_MDVP_Jitter_Abs_ - (column_MDVP_Jitter_ - column_MDVP_Shimmer))) - column_Shimmer_APQ3),0.747904,5.0
499,0.017332,column_MDVP_APQ,0.747904,0.2
506,0.018247,column_MDVP_APQ,0.747904,0.2
249,0.017332,column_MDVP_APQ,0.747904,0.2
381,0.017666,(column_RPDE - (((column_spread1 - column_MDVP_Flo_Hz_) + column_MDVP_Flo_Hz_) - ((column_Shimmer_APQ3 + column_Shimmer_APQ5) - (column_PPE - column_MDVP_Jitter_)))),0.746382,5.5
87,0.018339,(column_MDVP_Jitter_ - column_MDVP_RAP),0.741953,1.2
119,0.018339,(column_MDVP_Jitter_ - column_MDVP_RAP),0.741953,1.2
117,0.018339,(column_MDVP_Jitter_ - column_MDVP_RAP),0.741953,1.2
140,0.018339,(column_MDVP_Jitter_ - column_MDVP_RAP),0.741953,1.2
527,0.018450,((column_spread1 + column_D2) + column_MDVP_Jitter_Abs_),0.741448,2.2
545,0.018604,column_spread1,0.741448,0.2
625,0.018762,(((column_Shimmer_DDA + (column_Jitter_DDP + column_NHR)) + ((column_spread1 + column_MDVP_APQ) + (column_Jitter_DDP - column_Jitter_DDP))) - ((column_PPE - column_PPE) - column_MDVP_Shimmer)),0.741448,6.1
628,0.018061,(((column_MDVP_APQ + (column_Jitter_DDP - column_Jitter_DDP)) - ((column_MDVP_Fhi_Hz_ - column_Jitter_DDP) - column_Shimmer_DDA)) - ((column_MDVP_Shimmer - (column_MDVP_Fhi_Hz_ - column_MDVP_APQ)) - column_spread1)),0.741448,5.9
569,0.018445,(((column_MDVP_PPQ - column_Shimmer_DDA) + column_MDVP_APQ) + column_spread1),0.741448,3.2
652,0.018943,column_spread1,0.741448,0.2
561,0.018040,column_spread1,0.741448,0.2
535,0.017785,column_spread1,0.741448,0.2
470,0.018323,column_spread1,0.741448,0.2
469,0.018018,(column_Shimmer_APQ3 + (((column_spread1 + column_MDVP_RAP) + (column_Shimmer_APQ3 - column_MDVP_Jitter_)) + ((column_RPDE + column_DFA) - (column_DFA - column_PPE)))),0.741448,5.8
368,0.018401,column_spread1,0.741448,0.2
390,0.023072,((column_Shimmer_APQ5 + column_MDVP_RAP) - (((column_RPDE - column_Shimmer_APQ5) + column_MDVP_Shimmer) + column_spread1)),0.741448,4.5
419,0.018267,(((column_MDVP_Shimmer_dB_ - (column_Shimmer_APQ5 + column_MDVP_Shimmer_dB_)) - column_spread1) - column_MDVP_PPQ),0.741448,4.0
163,0.019762,column_spread1,0.741448,0.2